
try {
    // Code that might throw an exception
    // var y = 10 
    var x = y + 1;
    console.log(x)

} catch (error) {
    // Code to handle the exception
    console.error(error);
}
